import os

update_ods = ["sqoop --options-file sqoop_option.txt  --table ods_oitg --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_oitg --check-column etl_time  --incremental append --last-value '2018-08-24 03:49:37' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_oitt --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_oitt --check-column etl_time  --incremental append --last-value '2018-08-24 03:47:50' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_osal --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_osal --check-column etl_time  --incremental append --last-value '2019-01-03 03:48:51' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_ostr --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_ostr --check-column docdate  --incremental append --last-value '2019-01-02 22:33:51' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_owor --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_owor --check-column docdate  --incremental append --last-value '2019-01-02 18:29:20' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_owsl --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_owsl --check-column etl_time  --incremental append --last-value '2019-01-03 03:51:19' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_owsr --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_owsr --check-column etl_time  --incremental append --last-value '2019-01-03 03:51:57' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_sal1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_sal1 --check-column etl_time  --incremental append --last-value '2019-01-03 03:49:43' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_sal2 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_sal2 --check-column etl_time  --incremental append --last-value '2019-01-03 03:51:14' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_sck1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_sck1 --check-column etl_time  --incremental append --last-value '2019-01-03 03:54:36' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_str1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_str1 --check-column exitdate  --incremental append --last-value '2019-01-02 00:00:01' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_wor1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_wor1 --check-column duedate  --incremental append --last-value '2019-01-02 18:29:26' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_wsl1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_wsl1 --check-column etl_time  --incremental append --last-value '2019-01-03 03:50:55' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_wsr1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_wsr1 --check-column etl_time  --incremental append --last-value  '2019-01-03 03:51:01' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods",
          "sqoop --options-file sqoop_option.txt  --table ods_itm1 --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_itm1 --check-column etl_time  --incremental append --last-value '2019-01-03 03:46:58' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods"    ]

update_ods1 = ["sqoop --options-file sqoop_option.txt --table ods_target_product_turnover --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_target_product_turnover --check-column sale_date  --incremental append --last-value '2018-09-24' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
               "sqoop --options-file sqoop_option.txt  --table ods_product_bill_shop --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_product_bill_shop --check-column bill_date  --incremental append --last-value '2018-12-24' --null-string '\\\\N' --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
               "sqoop --options-file sqoop_option.txt  --table ods_product_bill_other --hive-database  rbu_sxcp_ods_dev  --hive-import --hive-table ods_product_bill_other --check-column bill_date  --incremental append --last-value '2018-12-24' --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1"]

print("增量导入ods数据")
for item in update_ods:
    os.system(item)

print("增量导入ods1数据")
for item in update_ods1:
    os.system(item)


all_ods1 = ["sqoop --options-file sqoop_option.txt --table ods_display --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_display  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_ocus --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_ocus  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_ohem --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_ohem  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_oitm --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_oitm  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_oshp --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_oshp  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_ousr --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_ousr  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_sa_personuprice_501 --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_sa_personuprice_501  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_sa_personuprice_801 --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_sa_personuprice_801  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_shelf_life --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_shelf_life  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_customer_501 --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_customer_501  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1",
            "sqoop --options-file sqoop_option.txt --table ods_customer_801 --hive-database  rbu_sxcp_ods_dev  --delete-target-dir --hive-import --hive-table ods_customer_801  --hive-overwrite --null-string '\\\\N'  --null-non-string '\\\\N' --hive-drop-import-delims -m 1 -- --schema ods1"]
print("全量导入ods1数据")
for item in all_ods1:
    os.system(item)
